# Change these first
owner: AutoFTbot # Your GitHub organization or username, where this repository lives
repo: Server-FT # The name of this repository

sites:
 - name: SG 1
   url: https://uhmyp.ftclouds.asia
   port: 80
 - name: Google DNS
   check: "tcp-ping"
   url: dns.google
   port: 53
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: Serverft.my.id
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/AutoFTbot/AutoFTbot/blob/main/assets/ft.png
  name: Server-FT
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data . No server required — just GitHub Actions, Issues, and Pages.


workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
